import type { Metadata } from "next";
import "./globals.css";
import { DragDropProvider } from "@/components/DraggableContext";
import { AuthProvider } from "./providers";

export const metadata: Metadata = {
  title: "Generate CV",
  description: "Generated by Generate CV",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className={`antialiased h-full `}>
        <AuthProvider>
          <DragDropProvider>
          {children}
          </DragDropProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
